name: Cypress Cucumber Tests

on: 
  workflow_dispatch:
  push:
    branches: ["main"]  

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run full-regression-headless-chrome 
      - name: Send results to Cucumber for Jira
        if: always()
        run: |
          curl -X POST https://c4j.cucumber.io/ci/rest/api/results \
          -H "authorization: Bearer ${{ secrets.C4J_TOKEN }}" \
          -H 'content-type: multipart/form-data' \
          -F results_file=@cucumber-report.json \
          -F language=js    